name: Rust Build

on:
  release:
    types: [published]

permissions:
  contents: write

# Cancel previous jobs that are running
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Build the project in release mode
        run: cargo build --release

      - name: Upload Release Binary
        id: upload-release-bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/stl2lnas
          asset_name: stl2lnas-bin
          asset_content_type: application/zip
